language: go

go:
  - "1.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

env:
  - GO111MODULE="on"

go_import_path: go.cryptoscope.co/ssb

install:
  - go get -t -v go.cryptoscope.co/ssb/...
